name: Update Laravel Tags
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn
      - run: yarn update-tags
      - name: Commit tags
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Auto-update tags"
          git push
