name: Update Laravel Tags

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn

      - run: yarn update-tags

      - name: Commit tags
        uses: EndBug/add-and-commit@v4
        with:
          message: "Auto-update tags"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
